CREATE DATABASE HouCell;
GO

USE HouCell;
GO

CREATE TABLE sobe(
	id INTEGER NOT NULL IDENTITY,
	ime VARCHAR(25) NOT NULL,
	PRIMARY KEY (id)
);
GO

CREATE TABLE tipiSenzorjev(
	id INTEGER NOT NULL IDENTITY,
	ime VARCHAR(25) NOT NULL,
	PRIMARY KEY (id)
);
GO

CREATE TABLE senzorji(
	idSenzor INTEGER NOT NULL IDENTITY,
	idSobe INTEGER NOT NULL,
	idTip INTEGER NOT NULL,
	vrednost INTEGER NOT NULL,
	PRIMARY KEY (idSenzor),
	FOREIGN KEY (idSobe) REFERENCES sobe(id),
	FOREIGN KEY (idTip) REFERENCES tipiSenzorjev(id)
);
GO

CREATE TABLE uporabniki(
	id INTEGER NOT NULL IDENTITY,
	ime VARCHAR(25) NOT NULL,
	geslo VARCHAR(25) NOT NULL,
	PRIMARY KEY (id)
);
GO